//get tests
###
GET https://cn483.brighton.domains/soundshare/src/server/api.php?chat=all

###
GET https://cn483.brighton.domains/soundshare/src/server/api.php?sender=2&receiver=2

###
GET https://cn483.brighton.domains/soundshare/src/server/api.php?sender=2

###
GET https://cn483.brighton.domains/soundshare/src/server/api.php?receiver=1

###
GET https://cn483.brighton.domains/soundshare/src/server/api.php?user=2